#!/bin/bash
# By: https://github.com/UserUnavailable

/home/anonimo/scripts/bar/bar.sh &

herbstclient pad 0 27
herbstclient set tree_style '╾│ ├└╼─┐'

herbstclient rename default W1
herbstclient add W2
herbstclient add W3
herbstclient add W4
herbstclient add W5
herbstclient add W6
herbstclient add W7
herbstclient add W8
herbstclient add W9

herbstclient set frame_gap 0
herbstclient set frame_border_width 0
herbstclient set frame_bg_transparent 1
herbstclient set frame_pandding 3

herbstclient set window_gap 10
herbstclient set window_border_width 3
herbstclient set window_border_normal_color "#282828"
herbstclient set window_border_active_color "#3ab8c9"

herbstclient mousebind Mod4-B1 move
herbstclient mousebind Mod4-B3 resize

herbstclient unrule -F
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on focus=on
