#!/bin/bash
# By: https://github.com/UserUnavailable

# Iniciar Bar
/home/anonimo/scripts/bar/bar2.sh &

# Facilitar nossa vida
hc() {
	herbstclient "${@}"
}

# Espaço para bar e tree_style
hc pad 0 20
hc set tree_style '╾│ ├└╼─┐'

# Setando Workspaces
hc rename default W1
hc add W2
hc add W3
hc add W4
hc add W5
hc add W6
hc add W7
hc add W8
hc add W9

# Configuração dos frame
hc set frame_gap 0
hc set frame_border_width 0
hc set frame_bg_transparent 1
hc set frame_padding 3

# Configuração das janelas
hc set window_gap 10
hc set window_border_width 4
hc set window_border_normal_color "#282828"
hc set window_border_active_color "#602733"

# Binds do mouse
hc mousebind Mod4-B1 move
hc mousebind Mod4-B3 resize

# Regras do wm
hc unrule -F
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on focus=on

# Para algumas BARs
hc rule windowtype="_NET_WM_WINDOW_TYPE_DOCK" manage=off
