#!/bin/bash
# By: https://github.com/UserUnavailable

## startup apps
$HOME/scripts/bar/lazyBar.sh &
setxkbmap -model abnt2 -layout br -variant abnt2 &

## to not write herbstclient 1001 times
hc() {
	herbstclient "${@}"
}

## bar space and tree_style
hc pad 0 30
hc set tree_style '╾│ ├└╼─┐'

## workspaces
hc rename default W1
hc add W2
hc add W3
hc add W4
hc add W5
hc add W6
hc add W7
hc add W8
hc add W9

## frame configuration
hc set frame_gap 0
hc set frame_border_width 0
hc set frame_bg_transparent 1
hc set frame_padding 3

## window configuration
hc set window_gap 10
hc set window_border_width 4
hc set window_border_normal_color "#282828"
hc set window_border_active_color "#cdcdcd"

## hotkeys
hc mousebind Mod4-B1 move
hc mousebind Mod4-B3 resize

## window manager rules
hc unrule -F
hc rule windowtype~"_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)" pseudotile=on focus=on
hc rule title="Media viewer" focus=on

## to not manage bar
hc rule windowtype="_NET_WM_WINDOW_TYPE_DOCK" manage=off
